# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcda65021530bbb88d643bb1a415148763a9f2e3bbe15ced54f3a536034ab60b24bd1fdf130d259234f85b23c00ad3e924844d472a2f0ad117fbf81dde9ade00

test:
  secret_key_base: b89bcac09f59f319a67a91b0317b4d070ec0577e3a2c5396cd0bf5338352b77147c4bf8ac2cc69f670438f26bf944771b8a92a9ecf517e96a557c93a65a5955b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
